### ISSUE TITLE
Stars get messed up with size of department and/or with zoom

### ISSUE THREAD

**Issue by loganbe11** [SethShickluna/COSC-4P02-R8Scholar#19]
![star_issue](https://user-images.githubusercontent.com/39658467/111407180-da993200-86a9-11eb-8976-796a56722f1a.PNG)

Stars will get shifted especially with the length of the one department name 
(Organizational Behaviour, Human Resource Management, Entrepreneurship and Ethics) 
the zoom of the page will also cause this issue

**Comment by lu16xx** [comment]
This also happens on the front page if using a smaller window size
![image](https://user-images.githubusercontent.com/77280537/111408949-6d3ad080-86ac-11eb-8729-0f681b1b3357.png)

**Comment by loganbe11** [comment]
Also an issue on insructor page 
![image](https://user-images.githubusercontent.com/39658467/111414507-7f217100-86b6-11eb-98b4-5c02e867e31d.png)

**Comment by SethShickluna** [comment]
fixed on account of long department names
