### ISSUE TITLE
Front Page issues

### ISSUE THREAD

**Issue by lu16xx** [SethShickluna/COSC-4P02-R8Scholar#20]
_MINOR VISUAL ISSUES_
-White text is not legible on the main page. Can be easily fixed by outlining or adding a backdrop/shadow
![image](https://user-images.githubusercontent.com/77280537/111409054-99eee800-86ac-11eb-89fd-a589dc3a1ffa.png)
-Can we guarantee symbol in sign up will not be broken on different systems? (If the prof opens our page, will it show as expected?)
![image](https://user-images.githubusercontent.com/77280537/111406611-fbad5300-86a8-11eb-97d3-998e78d3994b.png)

**Comment by SethShickluna** [comment]
1. fixed. 
2. pull this most recent version while testing, this is not an issue
