### ISSUE TITLE
Departments not properly updated upon page change

### ISSUE THREAD

**Issue by loganbe11** [SethShickluna/COSC-4P02-R8Scholar#21]
### This is the first page:
![image](https://user-images.githubusercontent.com/39658467/111407493-3fed2300-86aa-11eb-8bdc-f0ea9e52ca23.png)
### If you click on the second page, it will change the numbers but keep the information the same for departments:
![image](https://user-images.githubusercontent.com/39658467/111407543-4d0a1200-86aa-11eb-85e4-6a38c72b40ce.png)
### This is what the second page should look like, which is displayed by clicking on the second page again:
![image](https://user-images.githubusercontent.com/39658467/111407732-85a9eb80-86aa-11eb-8d55-906eb5cc97a4.png)
### If you then click back to the first page it will once again keep the second page information:
![image](https://user-images.githubusercontent.com/39658467/111407649-6e6afe00-86aa-11eb-9896-2663b2f7910f.png)

**Comment by SethShickluna** [comment]
fixed
