### ISSUE TITLE
User is not forced to verify upon log-in

### ISSUE THREAD

**Issue by lu16xx** [SethShickluna/COSC-4P02-R8Scholar#22]
Verification is not enforced.
![image](https://user-images.githubusercontent.com/77280537/111408318-7ecfa880-86ab-11eb-91b4-9c14573f2298.png)
I was able to change my password, but not my nickname while unverified.
![image](https://user-images.githubusercontent.com/77280537/111408578-dbcb5e80-86ab-11eb-8a6d-8049c1c54ed3.png)

**Comment by SethShickluna** [comment]
this is not a bug. closed
