### ISSUE TITLE
Instructors not appearing/ appearing wrong

### ISSUE THREAD

**Issue by loganbe11** [SethShickluna/COSC-4P02-R8Scholar#23]
Maurice Feldman|Applied Disability Studies( the first entry in instructors) appears under the wrong department:
![image](https://user-images.githubusercontent.com/39658467/111409097-aecb7b80-86ac-11eb-838f-188aa4e44c49.png)
Wendee Kubik|Women's and Gender Studies (the last entry in instructors) does not appear at all
![image](https://user-images.githubusercontent.com/39658467/111409151-c86cc300-86ac-11eb-9506-c7a26640bec1.png)

Note: first and last entries in department and courses are fine

**Comment by SethShickluna** [comment]
this was a issue with the instructor file. solved
