### ISSUE TITLE
Clicking last doesn't bring you to the last page

### ISSUE THREAD

**Issue by loganbe11** [SethShickluna/COSC-4P02-R8Scholar#25]
On the instructor page, clicking last doesn't bring you to the last page(38 is the last page with entries on it) 
As well as the course page, which again brings you to two before the last page (188 is last with entries)
Where as the department page brings you to 1 before the last page(3 is the last page with entries)
![image](https://user-images.githubusercontent.com/39658467/111409374-3618ef00-86ad-11eb-9c90-a9a25d16b5fe.png)
![image](https://user-images.githubusercontent.com/39658467/111409673-c9eabb00-86ad-11eb-9698-d13be6803b37.png)
![image](https://user-images.githubusercontent.com/39658467/111409742-ee469780-86ad-11eb-988c-c07040cf5449.png)

**Comment by SethShickluna** [comment]
fixed.
