### ISSUE TITLE
Clicking on department on instructors page searches wrong

### ISSUE THREAD

**Issue by loganbe11** [SethShickluna/COSC-4P02-R8Scholar#27]
Clicking on the department tries to go to the department page for the name of the instructor instead of the department
![image](https://user-images.githubusercontent.com/39658467/111410292-d885a200-86ae-11eb-8ba0-67e639bd1fa6.png)
![image](https://user-images.githubusercontent.com/39658467/111410362-f7843400-86ae-11eb-8d4f-d7bffe6da398.png)

**Comment by SethShickluna** [comment]
Fixed.
