### ISSUE TITLE
Wrong pathing for returns: 

### ISSUE THREAD

**Issue by loganbe11** [SethShickluna/COSC-4P02-R8Scholar#28]
Clicking on an instructor listed as "no data" in the departments page brings you to a page with a "return to instructors" message at the bottom (should be return to department) but clicking on that returns you to the courses page instead
![image](https://user-images.githubusercontent.com/39658467/111410678-90b34a80-86af-11eb-973a-0315e0cfff5a.png)
![image](https://user-images.githubusercontent.com/39658467/111410737-ab85bf00-86af-11eb-8433-8e9d2bb7cb7e.png)

**Comment by SethShickluna** [comment]
this is proper. closed.
