### ISSUE TITLE
Inconsistent ranks between pages:

### ISSUE THREAD

**Issue by loganbe11** [SethShickluna/COSC-4P02-R8Scholar#29]
The ranks for courses and instructors don't go up when swiching between pages( you'll see that i'm on page 5 but its still starts at 1), but the ranks for departments do go up between pages:
![image](https://user-images.githubusercontent.com/39658467/111411059-47172f80-86b0-11eb-9dd1-0a0d6a2d6797.png)
![image](https://user-images.githubusercontent.com/39658467/111411097-572f0f00-86b0-11eb-89db-76e620b470a2.png)

**Comment by SethShickluna** [comment]
fixed
