### ISSUE TITLE
Top Bar Burger Menu Issue

### ISSUE THREAD

**Issue by mp13ko** [SethShickluna/COSC-4P02-R8Scholar#30]
When having a window with less then half width (common when snapping window to side of the screen) The burger menu does the following when opened:
![TopBar1](https://user-images.githubusercontent.com/48832804/111411910-ceb16e00-86b1-11eb-819b-1816b977e455.png)
Then immediately after this it changes to:
![TopBar2](https://user-images.githubusercontent.com/48832804/111412095-251eac80-86b2-11eb-96b4-3bb241be9e87.png)
Expected outcome: Burger menu opens on the left side listing out courses, instructors, department, signup, and login.

**Comment by SethShickluna** [comment]
this has been looked at and slightly refactored, not apparent fix off the bat. marked as closed and will reopen during the next sprint
