### ISSUE TITLE
Top Bar R8SCHOLAR Button Causes New Tab

### ISSUE THREAD

**Issue by mp13ko** [SethShickluna/COSC-4P02-R8Scholar#31]
When clicking the R8SCHOLAR button on the homepage, it results in a new tab opening:
![TopBarNewTab](https://user-images.githubusercontent.com/48832804/111412397-bbeb6900-86b2-11eb-9945-5c305b8dc950.png)
Expected outcome: RBSCHOLAR button press results in the page being refreshed.

**Comment by SethShickluna** [comment]
fixed.
