### ISSUE TITLE
Search Glitches When Typing Fast

### ISSUE THREAD

**Issue by mp13ko** [SethShickluna/COSC-4P02-R8Scholar#33]
When typing fast, the search results glitch back the results from the first two letters as opposed to the whole word:
![SearchGlitch](https://user-images.githubusercontent.com/48832804/111412697-459b3680-86b3-11eb-89d1-dcd7d9765f97.png)
The expected result:
![SearchExpected](https://user-images.githubusercontent.com/48832804/111412878-97dc5780-86b3-11eb-942e-2e0115a5795b.png)

**Comment by SethShickluna** [comment]
unable to reproduce, not able to find a bug. closed.
