### ISSUE TITLE
Search Result Highlight Issue

### ISSUE THREAD

**Issue by mp13ko** [SethShickluna/COSC-4P02-R8Scholar#34]
The search result highlighting has two issues:

![SearchHighlighting](https://user-images.githubusercontent.com/48832804/111413525-c9a1ee00-86b4-11eb-86c8-3f299f934440.png)

1. If you press on the highlighted area of a result without pressing on the text, the area stays highlighted even after you move the cursor away.

Expected outcome: When clicking on the highlighted area of a result, it should be considered as if the user is choosing that result. 
 
2. Highlighted area is too dark, makes text hard to read. Should be changed to a lighter gray.

**Comment by feesh42** [comment]
Fixed. Made the list item border radius 0. Changed text color to white when highlighted. Changed menu border radius to 14. Pushed changes to structure_fix_2. EDIT: Also removed <a> tag for menu items, and added href to the MenuItem Component.
![Capture](https://user-images.githubusercontent.com/69432654/111681766-eb6db300-8823-11eb-89fe-d0b21ce49469.PNG)
