### ISSUE TITLE
Search Bar Outline

### ISSUE THREAD

**Issue by mp13ko** [SethShickluna/COSC-4P02-R8Scholar#35]
Clicking on the area directly around the search bar results in a visible outline (not the same as the outline you get when clicking on the actual search bar.
![SearchBarOutline](https://user-images.githubusercontent.com/48832804/111413664-11287a00-86b5-11eb-8481-4f54f4423add.png)
Expected outcome: It should only be possible to click inside the search bar.

**Comment by SethShickluna** [comment]
fixed.
