### ISSUE TITLE
option to sort by instructor name instead of department name for instructors page

### ISSUE THREAD

**Issue by loganbe11** [SethShickluna/COSC-4P02-R8Scholar#37]
An option to sort: instructor A-Z Z-A in addition to department A-Z, Z-A in instructors page 
![image](https://user-images.githubusercontent.com/39658467/111416476-6d41cd00-86ba-11eb-9d98-4d0677e9e6b4.png)

**Comment by SethShickluna** [comment]
closed. fixed by grant
