### ISSUE TITLE
Reviews: New Nickname Doesn't Update On Old Reviews

### ISSUE THREAD

**Issue by mp13ko** [SethShickluna/COSC-4P02-R8Scholar#38]
When you change your nickname it doesn’t update the old reviews with the new nickname.
![ReviewNicknames](https://user-images.githubusercontent.com/48832804/111416828-083aa700-86bb-11eb-8924-9e4bce0e9232.png)
Expected outcome: Old reviews should be having your current nickname. 
![ReviewNicknames2](https://user-images.githubusercontent.com/48832804/111416891-2d2f1a00-86bb-11eb-8380-46965c056fbf.png)

**Comment by SethShickluna** [comment]
Not a current issue, will be addressed in the upcoming weeks
