### ISSUE TITLE
Lack of consistency between "Login" and "Sign in"

### ISSUE THREAD

**Issue by lu16xx** [SethShickluna/COSC-4P02-R8Scholar#40]
![image](https://user-images.githubusercontent.com/77280537/111482103-f6ccbb80-8709-11eb-84e4-c028a02e60b3.png)
![image](https://user-images.githubusercontent.com/77280537/111482145-fcc29c80-8709-11eb-85f5-815d91aa9e4b.png)
![image](https://user-images.githubusercontent.com/77280537/111482166-03e9aa80-870a-11eb-9902-82514f6b8d9d.png)
Should be an easy fix, just rename the login button, or the sign in and sign out buttons, depending on which way we want to go.

**Comment by SethShickluna** [comment]
changed. closed
