### ISSUE TITLE
Add Error messages to signup

### ISSUE THREAD

**Issue by lu16xx** [SethShickluna/COSC-4P02-R8Scholar#41]
When creating an account, it can be unclear what the user is doing wrong in the event of an error.
![image](https://user-images.githubusercontent.com/77280537/111483037-cfc2b980-870a-11eb-99e0-34582b11eb47.png)
There should be a way to let the user know whether they have an email error, a username error, a password error, and what the error is.

**Comment by SethShickluna** [comment]
put a bandaid over this, will come back to it with an elegant solution within the next sprint
