### ISSUE TITLE
Editing users as an Admin is not possible due to password length error

### ISSUE THREAD

**Issue by lu16xx** [SethShickluna/COSC-4P02-R8Scholar#44]
![image](https://user-images.githubusercontent.com/77280537/111550503-a169cc00-8754-11eb-8081-8063d1875a92.png)

**Comment by lu16xx** [comment]
Field length seems to be a recurring issue. Also occurs with departments:
![image](https://user-images.githubusercontent.com/77280537/111550985-9cf1e300-8755-11eb-9d21-b1c85e2dac43.png)
and courses:
![image](https://user-images.githubusercontent.com/77280537/111551031-af6c1c80-8755-11eb-9db7-94a87c463246.png)
Instructors seem to be fine

**Comment by GrantNike** [comment]
I fixed this bug, it was an error in the model(database table) definitions.
