### ISSUE TITLE
Certain instructors are merged together as one

### ISSUE THREAD

**Issue by lu16xx** [SethShickluna/COSC-4P02-R8Scholar#45]
![image](https://user-images.githubusercontent.com/77280537/111551380-71232d00-8756-11eb-9e42-f94755bd1baf.png)
![image](https://user-images.githubusercontent.com/77280537/111551190-05d95b00-8756-11eb-878c-2514d1d4767a.png)
![image](https://user-images.githubusercontent.com/77280537/111551222-1be71b80-8756-11eb-8fee-3d0d13d4bda3.png)
![image](https://user-images.githubusercontent.com/77280537/111551262-34efcc80-8756-11eb-9a07-ee81dd32530f.png)
![image](https://user-images.githubusercontent.com/77280537/111551329-58b31280-8756-11eb-83bb-bfd00f6a6aac.png)

**Comment by SethShickluna** [comment]
this is not an issue. due to an error in the instructors.txt file

**Comment by loganbe11** [comment]
I'll start fixing this now

**Comment by loganbe11** [comment]
nevermind, I see that it was already done
