### ISSUE TITLE
Rating doesn't update upon review delete

### ISSUE THREAD

**Issue by loganbe11** [SethShickluna/COSC-4P02-R8Scholar#47]
If a review is deleted (was through admin), the review will no longer be displayed but the rating won't update
![image](https://user-images.githubusercontent.com/39658467/111566964-8eff8a80-8774-11eb-966b-f0ebbc9f654c.png)
![image](https://user-images.githubusercontent.com/39658467/111567071-bc4c3880-8774-11eb-9af7-bef64cdf59d3.png)
This also affected the department displayed instructor rating
![image](https://user-images.githubusercontent.com/39658467/111567309-1c42df00-8775-11eb-8da0-2a86efe19fed.png)

**Comment by SethShickluna** [comment]
marked as wontfix. this is a known issue and will require some backend structure to be modified. next steps TBD

**Comment by SethShickluna** [comment]
closed. this is addressed in the deletion step
